name: Secret Value found!

on:

push:

public:

jobs:

scan:

name: gitleaks

runs-on: windows-latest

steps:

- name: Checkout

uses: actions/checkout@v3

- name: Get the dir

run: |

dir

- name: Install the gitleaks

run: ./install.ps1

shell: pwsh

- name: Generate the report

run: C:\gitleaks\gitleaks.exe detect -s D:\a\TestPublicProject\TestPublicProject -f json -r D:/leaksreport.json

shell: pwsh

continue-on-error: true

- name: Check file existence

id: check_files

uses: andstor/file-existence-action@v1

with:

files: "D:/leaksreport.json"

exit 1
